sudo: false
language: python
env:
  global:
    - NOSE_NOLOGCAPTURE=true
    - NOSE_VERBOSE=2
    - NOSE_WITH_COVERAGE=true
    - NOSE_COVER_PACKAGE=neovim
  matrix:
    - CI_TARGET=tests
matrix:
  include:
    - python: 2.7
      env: CI_TARGET=flake
    - python: 3.4
      env: CI_TARGET=flake
python:
  # If the build matrix gets bigger, also update the number of runs
  # at the bottom of .scrutinizer.yml.
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - 3.6
  - pypy
before_install:
  - if [ $CI_TARGET = tests ]; then
      eval "$(curl -Ss https://raw.githubusercontent.com/neovim/bot-ci/master/scripts/travis-setup.sh) nightly-x64";
      pip install -q scrutinizer-ocular tox-travis;
    else
      pip install -q flake8 flake8-import-order flake8-docstrings pep8-naming;
    fi
install:
  - pip install .
script:
  - if [ $CI_TARGET = tests ]; then
      tox;
    else
      flake8 neovim;
    fi
after_script:
  - if [ $CI_TARGET = tests ]; then
      ocular;
    fi
