language: python
python:
  - "2.6"
  - "2.7"
before_install:
  - sudo apt-get install expect
  - git clone --depth=1 -b master git://github.com/neovim/neovim nvim
  - cd /opt && sudo git clone --depth=1 git://github.com/neovim/deps neovim-deps && cd -
install:
  - pip install .
  - prefix="/opt/neovim-deps"
  - eval $($prefix/bin/luarocks path)
  - export PATH="$prefix/bin:$PATH"
  - export PKG_CONFIG_PATH="$prefix/lib/pkgconfig"
  - export USE_BUNDLED_DEPS=OFF
  - cd nvim && make && cd ..
script:
  - ./nvim/scripts/run-api-tests.exp "nosetests --nologcapture --verbosity=2" "./nvim/build/bin/nvim -u NONE"
  - NVIM_SPAWN_ARGV='["./nvim/build/bin/nvim", "-u", "NONE", "--embed"]'  nosetests --nologcapture --verbosity=2
