sudo: false
language: python
env:
  global:
    - NOSE_NOLOGCAPTURE=true
    - NOSE_VERBOSE=2
    - NOSE_WITH_COVERAGE=true
    - NOSE_COVER_PACKAGE=neovim
    - PYTEST_ADDOPTS=-vv
  matrix:
    - CI_TARGET=tests
matrix:
  include:
    - python: 3.6
      env: CI_TARGET=checkqa TOXENV=checkqa
python:
  # If the build matrix gets bigger, also update the number of runs
  # at the bottom of .scrutinizer.yml.
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - pypy
before_install:
  - if [ $CI_TARGET = tests ]; then
      eval "$(curl -Ss https://raw.githubusercontent.com/neovim/bot-ci/master/scripts/travis-setup.sh) nightly-x64";
      pip install -q scrutinizer-ocular tox-travis;
    else
      pip install -q tox;
    fi
install:
  - pip install .
script:
  - tox
after_script:
  - if [ $CI_TARGET = tests ]; then
      ocular;
    fi
