dist: xenial
language: python
env:
  global:
    - PYTEST_ADDOPTS=-vv
  matrix:
    - CI_TARGET=tests
matrix:
  include:
    - python: pypy
      dist: trusty
      sudo: false
    - python: 3.6
      env: CI_TARGET=checkqa TOXENV=checkqa
python:
  # If the build matrix gets bigger, also update the number of runs
  # at the bottom of .scrutinizer.yml.
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - 3.7
before_install:
  - if [ $CI_TARGET = tests ]; then
      eval "$(curl -Ss https://raw.githubusercontent.com/neovim/bot-ci/master/scripts/travis-setup.sh) nightly-x64";
      pip install -q scrutinizer-ocular tox-travis;
    else
      pip install -q tox;
    fi
script:
  - tox
after_script:
  - if [ $CI_TARGET = tests ]; then
      coverage combine;
      coverage report -m;
      coverage xml;
      bash <(curl --retry 5 --silent --fail https://codecov.io/bash) -f coverage.xml;
      ocular;
    fi
